<h1 dir=rtl align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
تشخیص معدل دانش آموزان</font>
</h1>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
در این سوال قصد داریم با استفاده از یک مجموعه‌داده که شامل اطلاعات دانش‌آموزان است، معدل آن‌ها را تخمین بزنیم. برای این‌کار شما باید پس از پیش‌پردازش داده‌ها، به مهندسی ویژگی و ساخت مدل مناسب بپردازید. توجه داشته باشید، در انتها، تنها مدل شما مورد بررسی قرار خواهد گرفت، اما مسلماً هرچه پیش‌پردازش و مهندسی ویژگی بهتری داشته باشید در نهایت به مدل بهتری خواهید رسید.

</font>
</p>

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معرفی مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    در فایل اولیه‌ی این سوال یک پوشه با نام <code>data</code> قرار دارد.
    این پوشه شامل دو فایل با نام‌های <code>train.csv</code> و <code>test.csv</code> است که به‌ترتیب مجموعه‌داده‌ی آموزش و آزمون هستند.
    مجموعه‌داده‌ی آموزش این سوال شامل ۱۹۱۳ سطر و ۱۴ ستون است و
        مجموعه‌داده‌ی آزمون دارای ۴۷۹ سطر است و تنها ستون <code>GPA</code> را ندارد.
    توضیحات مربوط به ستون‌ها به شرح زیر است:
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>

| <b>نام ویژگی</b> | <b>توضیح ویژگی</b> |
| :---: | :---: |
| <code>StudentID</code> | شماره‌ی دانش‌آموزی|
| <code>Age</code> | سن فرد|
| <code>Gender</code> | جنسیت، ۰ برای آقایان و ۱ برای خانم‌ها|
| <code>Ethnicity</code> |قومیت دانش‌آموزان|
| <code>ParentalEducation</code> |سطح تصحیلات خانواده‌ی دانش‌آموز|
| <code>StudyTimeWeekly</code> | ساعت مطالعه‌ی هفتگی از ۰ تا ۲۰ ساعت|
| <code>Absences</code> | تعداد غیبت دانش‌آموز در یک سال تحصیلی از ۰ تا ۳۰|
| <code>Tutoring</code> | وضعیت تدریس خصوصی، ۰ نشان‌دهنده‌ی خیر و ۱ نشان‌دهنده بله|
| <code>ParentalSupport</code> | میزان حمایت والدین از دانش‌آموز|
| <code>Extracurricular</code> | شرکت در برنامه‌های فوق‌برنامه، ۰ نشان‌دهنده‌ی خیر و ۱ نشان‌دهنده‌ی بله|
| <code>Sports</code> | شرکت در برنامه‌های ورزشی، ۰ نشان‌دهنده‌ی خیر و ۱ نشان‌دهنده‌ی بله||
| <code>Music</code> | شرکت در برنامه‌های موسیقی، ۰ نشان‌دهنده‌ی خیر و ۱ نشان‌دهنده‌ی بله||
| <code>Volunteering</code> | شرکت در برنامه‌های داوطلبانه، ۰ نشان‌دهنده‌ی خیر و ۱ نشان‌دهنده‌ی بله||
| <code>GPA</code> | میانگین نمره در بازه‌ی صفر تا چهار|

</font>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:500%; font-family:vazir; font-size:medium">
<font color="red" size=3><b color='red'>توجه:</b></font>
<font face="vazir" size=3>
داده‌های ارزیابی ممکن است داده‌ی گم‌شده (Nan) داشته باشند.
</font>
</p>

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
خواندن مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    در ابتدا نیاز است فایل‌های مجموعه‌داده را بخوانید. نمونه‌های آموزشی در فایل <code>train.csv</code> و نمونه‌های آزمون که باید مقدار متغیر هدف آن‌ها را پیش‌بینی کنید در فایل <code>test.csv</code> ذخیره شده‌اند. اگر لازم دانستید می‌توانید به دلخواه خود بخشی از مجموعه‌ی آموزش را به عنوان مجموعه‌ی اعتبارسنجی نیز جدا کنید.
</font>
</p>

In [322]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn import tree
from sklearn import ensemble
from sklearn import svm
from sklearn import neighbors
from sklearn import metrics
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [323]:
# Reading/Loading the dataset files
data_train = pd.read_csv("../data/train.csv")
data_test = pd.read_csv("../data/test.csv")

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
پیش‌پردازش و مهندسی ویژگی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
        در این سوال شما می‌توانید از هر تکنیک پیش‌پردازش/مهندسی ویژگی دلخواهتان، استفاده کنید.
    <br>
    تکنیک‌هایی که استفاده می‌کنید به شکل مستقیم مورد ارزیابی توسط سامانه داوری قرار <b>نمی‌گیرند.</b> بلکه همه آن‌ها در دقت مدل شما تاثیر خواهند گذاشت؛ بنابراین هر چه پیش‌پردازش/مهندسی ویژگی بهتری انجام دهید تا دقت مدل بهبود پیدا کند، امتیاز بیشتری از این سوال کسب خواهید کرد.

</font>
</p>

In [324]:
# Preprocessing step
data_train = data_train.drop("StudentID",axis=1)
data_test = data_test.drop("StudentID",axis=1)

data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1913 entries, 0 to 1912
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                1913 non-null   int64
 1   Gender             1913 non-null   int64
 2   Ethnicity          1913 non-null   object
 3   ParentalEducation  1731 non-null   object
 4   StudyTimeWeekly    1913 non-null   float64
 5   Absences           1913 non-null   int64
 6   Tutoring           1913 non-null   int64
 7   ParentalSupport    1751 non-null   object
 8   Extracurricular    1913 non-null   int64
 9   Sports             1913 non-null   int64
 10  Music              1913 non-null   int64
 11  Volunteering       1913 non-null   int64
 12  GPA                1913 non-null   float64
dtypes: float64(2), int64(8), object(3)
memory usage: 194.4+ KB

In [325]:
data_train.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,1913.0,16.456351,1.124705,15.000000,15.000000,16.000000,17.000000,18.000000
Gender,1913.0,0.514375,0.499924,0.000000,0.000000,1.000000,1.000000,1.000000
StudyTimeWeekly,1913.0,9.748506,5.702764,0.008031,4.958649,9.518844,14.407464,19.968425
Absences,1913.0,14.618400,8.485326,0.000000,7.000000,15.000000,22.000000,29.000000
Tutoring,1913.0,0.302143,0.459307,0.000000,0.000000,0.000000,1.000000,1.000000
Extracurricular,1913.0,0.380031,0.485521,0.000000,0.000000,0.000000,1.000000,1.000000
Sports,1913.0,0.304757,0.460425,0.000000,0.000000,0.000000,1.000000,1.000000
Music,1913.0,0.198118,0.398686,0.000000,0.000000,0.000000,0.000000,1.000000
Volunteering,1913.0,0.156299,0.363234,0.000000,0.000000,0.000000,0.000000,1.000000
GPA,1913.0,1.901119,0.916532,0.000000,1.162574,1.886543,2.621623,4.000000

In [326]:
data_train["Ethnicity"].value_counts()

Ethnicity
Caucasian           975
African American    386
Asian               372
Other               180
Name: count, dtype: int64

In [327]:
print(data_train["ParentalEducation"].value_counts())
print("------------------------------------------")

print(data_train["ParentalSupport"].value_counts())
print("------------------------------------------")

mode_ParentalEducation = data_train["ParentalEducation"].mode()[0]
print(mode_ParentalEducation)

print("------------------------------------------")
mode_ParentalSupport = data_train["ParentalSupport"].mode()[0]
print(mode_ParentalSupport)

ParentalEducation
Some College    757
High School     576
Bachelor        307
Higher           91
Name: count, dtype: int64
------------------------------------------
ParentalSupport
Moderate     597
High         560
Low          385
Very High    209
Name: count, dtype: int64
------------------------------------------
Some College
------------------------------------------
Moderate

In [328]:
print(data_train.isnull().sum())

Age                    0
Gender                 0
Ethnicity              0
ParentalEducation    182
StudyTimeWeekly        0
Absences               0
Tutoring               0
ParentalSupport      162
Extracurricular        0
Sports                 0
Music                  0
Volunteering           0
GPA                    0
dtype: int64

In [329]:
data_train["ParentalEducation"] = data_train["ParentalEducation"].fillna(mode_ParentalEducation)

data_train["ParentalSupport"] = data_train["ParentalSupport"].fillna(mode_ParentalSupport)

data_test["ParentalEducation"] = data_test["ParentalEducation"].fillna(mode_ParentalEducation)

data_test["ParentalSupport"] = data_test["ParentalSupport"].fillna(mode_ParentalSupport)

In [330]:
data_train['ParentalSupport']=data_train['ParentalSupport'].replace({
    "Low":0, "Moderate":1, "High":2, "Very High":3}).astype(int)

data_train['ParentalEducation']=data_train['ParentalEducation'].replace({
    "High School":0, "Some College":1, "Bachelor":2, "Higher":3}).astype(int)

data_test['ParentalSupport']=data_test['ParentalSupport'].replace({
    "Low":0, "Moderate":1, "High":2, "Very High":3}).astype(int)

data_test['ParentalEducation']=data_test['ParentalEducation'].replace({
    "High School":0, "Some College":1, "Bachelor":2, "Higher":3}).astype(int)

/var/folders/rw/j7c6vw4s1hl90fjq5cy_xp_80000gn/T/ipykernel_74652/830312273.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data_train['ParentalSupport']=data_train['ParentalSupport'].replace({
/var/folders/rw/j7c6vw4s1hl90fjq5cy_xp_80000gn/T/ipykernel_74652/830312273.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data_train['ParentalEducation']=data_train['ParentalEducation'].replace({
/var/folders/rw/j7c6vw4s1hl90fjq5cy_xp_80000gn/T/ipykernel_74652/830312273.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data_test['ParentalSupport']=data_test['ParentalSupport'].replace({
/var/folders/rw/j7c6vw4s1hl90fjq5cy_xp_80000gn/T/ipykernel_74652/830312273.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data_test['ParentalEducation']=data_test['ParentalEducation'].replace({

In [331]:
le=preprocessing.LabelEncoder()

data_train["Ethnicity"]=le.fit_transform(data_train["Ethnicity"])

data_test["Ethnicity"]=le.transform(data_test["Ethnicity"])

In [332]:
data_train.corr()["GPA"]

Age                 -0.000479
Gender              -0.009432
Ethnicity           -0.018839
ParentalEducation   -0.055249
StudyTimeWeekly      0.194446
Absences            -0.918941
Tutoring             0.142341
ParentalSupport      0.148689
Extracurricular      0.084580
Sports               0.070540
Music                0.096042
Volunteering         0.003967
GPA                  1.000000
Name: GPA, dtype: float64

In [333]:
x = data_train.drop("GPA",axis=1)
y = data_train["GPA"]

In [334]:
x_train, x_valid, y_train, y_valid = train_test_split(
    x, y, test_size=0.2, random_state=42
)

x_train.shape, x_valid.shape, y_train.shape, y_valid.shape

((1530, 12), (383, 12), (1530,), (383,))

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
آموزش مدل
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    حال که داده را پاکسازی کرده و احتمالا ویژگی‌هایی را به آن افزوده یا از آن حذف کرده‌اید، وقت آن است که مدلی آموزش دهید که بتواند متغیر هدف این مسئله را پیش‌بینی کند.
</font>
</p>

In [335]:
# Model design
model_1 = linear_model.LinearRegression()
model_1.fit(x_train,y_train)

model_2 = tree.DecisionTreeRegressor()
model_2.fit(x_train,y_train)

model_3 = ensemble.RandomForestRegressor()
model_3.fit(x_train,y_train)

model_4 = svm.SVR()
model_4.fit(x_train,y_train)

model_5 = neighbors.KNeighborsRegressor(20)
model_5.fit(x_train,y_train)

model_6 = Sequential()
model_6.add(Dense(32,activation="relu",input_shape=x_train.iloc[0].shape))
model_6.add(Dense(1,activation="linear"))
model_6.compile(optimizer="adam", loss="mae")
model_6.fit(x_train, y_train, epochs=20, validation_data=(x_valid,y_valid))
model_6.summary()

Epoch 1/20

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/keras/src/layers/core/dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.5035 - val_loss: 1.2344
Epoch 2/20
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - loss: 0.6258 - val_loss: 0.3854
Epoch 3/20
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - loss: 0.3578 - val_loss: 0.3133
Epoch 4/20
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - loss: 0.3032 - val_loss: 0.2627
Epoch 5/20
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - loss: 0.2866 - val_loss: 0.2832
Epoch 6/20
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - loss: 0.2726 - val_loss: 0.2266
Epoch 7/20
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - loss: 0.2671 - val_loss: 0.2275
Epoch 8/20
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - loss: 0.2555 - val_loss: 0.2225
Epoch 9/20
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - loss: 0.2532 - val_loss: 0.2607
Epoch 10/20
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - loss: 0.2485 - val_loss: 0.2216
Epoch 11/20
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 972us/step - loss: 0.2404 - val_loss: 0.2224
Epoch 12/20
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - loss: 0.2382 - val_loss: 0.2284
Epoch 13/20
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - loss: 0.2374 - val_loss: 0.2156
Epoch 14/20
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - loss: 0.2371 - val_loss: 0.2245
Epoch 15/20
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - loss: 0.2397 - val_loss: 0.2431
Epoch 16/20
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - loss: 0.2366 - val_loss: 0.2225
Epoch 17/20
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - loss: 0.2399 - val_loss: 0.2627
Epoch 18/20
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - loss: 0.2389 - val_loss: 0.2121
Epoch 19/20
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - loss: 0.2344 - val_loss: 0.2108
Epoch 20/20
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - loss: 0.2267 - val_loss: 0.2209

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_20 (Dense)                │ (None, 32)             │           416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_21 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,349 (5.27 KB)

 Trainable params: 449 (1.75 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 900 (3.52 KB)

In [339]:
x_train.iloc[0].shape

(12,)

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معیار ارزیابی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    معیاری که برای ارزیابی عملکرد مدل انتخاب کرده‌ایم، <code>r2_score</code> نام دارد.
    <br>
    این معیار، سنجه ارزیابی کیفیت مدل شماست. به عبارت بهتر در سامانه داوری هم از همین معیار برای نمره‌دهی استفاده شده است.
    <br>
    پیشنهاد می‌شود با توجه به این معیار، عملکرد مدل خود را بر روی مجموعه‌ی آموزش یا اعتبارسنجی ارزیابی کنید.
</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font color="red"><b color='red'>توجه:</b></font>
<font face="vazir" size=3>
    برای دریافت نمره از این سوال لازم است تا دقت مدل شما از آستانه‌ی ۰.۴ بیشتر باشد.
    در صورتی که دقت مدل شما از ۰.۴ کمتر باشد نمره شما 
    <b>صفر</b>
    خواهد شد و در غیر این صورت با فرمول زیر محاسبه می‌شود:
</font>
</p>

In [336]:
# evaluate your model
from sklearn.metrics import r2_score

# داده را به آموزش و ارزیابی تقسیم کن
# مدل را روی داده های validation ارزیابی کنید
pred_1 = model_1.predict(x_valid)
res_1 = metrics.r2_score(y_valid,pred_1)
pred_2 = model_2.predict(x_valid)
res_2 = metrics.r2_score(y_valid,pred_2)
pred_3 = model_3.predict(x_valid)
res_3 = metrics.r2_score(y_valid,pred_3)
pred_4 = model_4.predict(x_valid)
res_4 = metrics.r2_score(y_valid,pred_4)
pred_5 = model_5.predict(x_valid)
res_5 = metrics.r2_score(y_valid,pred_5)
pred_6 = model_6.predict(x_valid)
res_6 = metrics.r2_score(y_valid,pred_6)

res_list = [res_1,res_2,res_3,res_4,res_5,res_6]
for i in range(6):
    print(f"r2-score for model_{i+1} = ",res_list[i])

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
r2-score for model_1 =  0.9408380351319378
r2-score for model_2 =  0.8416223086731739
r2-score for model_3 =  0.9256747075135775
r2-score for model_4 =  0.938982966012129
r2-score for model_5 =  0.9016874021043958
r2-score for model_6 =  0.9085020137162658

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
 پیش‌بینی بر روی داده‌ی تست و خروجی
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    پیش‌بینی مدل خود بر روی داده‌های آزمون را در یک دیتافریم (<code>dataframe</code>) به فرمت زیر ذخیره کنید.
</font>
</p>


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    توجه داشته باشید که نام دیتافریم باید <code>submission</code> باشد؛ در غیر این‌صورت، سامانه‌ی داوری قادر به ارزیابی خروجی شما نخواهد بود.
    این دیتافریم تنها شامل ۱ ستون با اسم <code>GPA</code> است و ۴۷۹ سطر دارد.
    <br>
    به ازای هر سطر موجود در مجموعه‌داده‌ی آزمون، باید یک مقدار پیش‌بینی‌شده داشته باشید.
    به‌عنوان مثال جدول زیر، ۵ سطر ابتدایی دیتافریم <code>submission</code> را نشان می‌دهد. البته این اعداد به‌صورت فرضی هستند و در جواب شما، اعداد ستون <code>GPA</code> ممکن است متفاوت باشند.
</font>
</p>

<center>
<div style="direction: ltr;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
||<code>GPA</code>|
|:----:|:-----:|
|0|2.6765|
|1|3.9865434|
|2|1.0323434|
|3|0.0434253|
|4|2.060680|

</font>
</div>
</center>

In [337]:
# To-Do
y_1 = np.array(list(model_1.predict(data_test)))
y_2 = np.array(list(model_2.predict(data_test)))
y_3 = np.array(list(model_3.predict(data_test)))
y_4 = np.array(list(model_4.predict(data_test)))
y_5 = np.array(list(model_5.predict(data_test)))
y_6 = np.array(list(model_6.predict(data_test).ravel()))
y_out = (y_1*res_list[0] + y_2*res_list[1] + y_3*res_list[2] + y_4*res_list[3] + y_5*res_list[4] + y_6*res_list[5])/6
submission = pd.DataFrame(model_1.predict(data_test),columns=["GPA"])
submission

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 725us/step

          GPA
0    1.421955
1    2.856473
2    1.747971
3    3.512443
4    0.210225
..        ...
474  1.772410
475  2.152588
476  2.547283
477  2.443557
478  0.805423

[479 rows x 1 columns]

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) در غیر این صورت، در پایان مسابقه نمره شما به صفر تغییر خواهد کرد.
    <br>
    همچنین اگر از کولب برای اجرای این فایل نوت‌بوک استفاده می‌کنید، قبل از ارسال فایل <code>result.zip</code>، آخرین نسخه‌ی نوت‌بوک خود را دانلود کرده و داخل فایل ارسالی قرار دهید.
</font>

In [338]:
import zipfile
import os

if not os.path.exists(os.path.join(os.getcwd(), 'Student_GPA.ipynb')):
    %notebook -e Student_GPA.ipynb

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

submission.to_csv('submission.csv', index=False)

file_names = ['Student_GPA.ipynb', 'submission.csv']
compress(file_names)

File Paths:
['Student_GPA.ipynb', 'submission.csv']